services:
  api:
    build:
      context: ./api
    image: labinvent-test-api:latest
    container_name: labinvent-test-api
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx256m
    networks:
      - labinvent-net

  ui:
    build:
      context: ./ui
    image: labinvent-test-ui:latest
    container_name: labinvent-test-ui
    ports:
      - "8081:80"
    depends_on:
      - api
    networks:
      - labinvent-net

networks:
  labinvent-net:
    driver: bridge
